"""initial_workflow_schema

Revision ID: f69e41b953b6
Revises:
Create Date: 2026-09-15 18:02:11.973168

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f69e41b953b6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_stage", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflows_current_stage"), "workflows", ["current_stage"], unique=False
    )
    op.create_index(
        op.f("ix_workflows_idempotency_key"), "workflows", ["idempotency_key"], unique=True
    )
    op.create_index(op.f("ix_workflows_status"), "workflows", ["status"], unique=False)
    op.create_index(
        "ix_workflows_status_stage", "workflows", ["status", "current_stage"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("logical_key", sa.String(length=255), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("current_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "input_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "logical_key", name="uq_jobs_workflow_logical_key"),
    )
    op.create_index(op.f("ix_jobs_available_at"), "jobs", ["available_at"], unique=False)
    op.create_index("ix_jobs_claim_poll", "jobs", ["status", "available_at"], unique=False)
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_stage"), "jobs", ["stage"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_workflow_id"), "jobs", ["workflow_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("gdrive_file_id", sa.String(length=255), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=50), nullable=False),
        sa.Column(
            "artifact_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_artifact_type"), "artifacts", ["artifact_type"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_gdrive_file_id"), "artifacts", ["gdrive_file_id"], unique=False
    )
    op.create_index(op.f("ix_artifacts_job_id"), "artifacts", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_artifacts_lifecycle_status"), "artifacts", ["lifecycle_status"], unique=False
    )
    op.create_index(op.f("ix_artifacts_workflow_id"), "artifacts", ["workflow_id"], unique=False)
    op.create_index(
        "ix_artifacts_workflow_type", "artifacts", ["workflow_id", "artifact_type"], unique=False
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("provider_operation_id", sa.String(length=500), nullable=True),
        sa.Column("submission_token", sa.String(length=500), nullable=True),
        sa.Column(
            "request_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "response_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "attempt_number", name="uq_job_attempts_job_attempt"),
    )
    op.create_index(
        op.f("ix_job_attempts_heartbeat_at"), "job_attempts", ["heartbeat_at"], unique=False
    )
    op.create_index(op.f("ix_job_attempts_job_id"), "job_attempts", ["job_id"], unique=False)
    op.create_index(
        "ix_job_attempts_lease",
        "job_attempts",
        ["job_id", "worker_id", "lease_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_attempts_lease_token"), "job_attempts", ["lease_token"], unique=False
    )
    op.create_index(
        op.f("ix_job_attempts_provider_operation_id"),
        "job_attempts",
        ["provider_operation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_job_attempts_status"), "job_attempts", ["status"], unique=False)
    op.create_index(
        op.f("ix_job_attempts_submission_token"), "job_attempts", ["submission_token"], unique=False
    )
    op.create_index(op.f("ix_job_attempts_worker_id"), "job_attempts", ["worker_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_attempts_worker_id"), table_name="job_attempts")
    op.drop_index(op.f("ix_job_attempts_submission_token"), table_name="job_attempts")
    op.drop_index(op.f("ix_job_attempts_status"), table_name="job_attempts")
    op.drop_index(op.f("ix_job_attempts_provider_operation_id"), table_name="job_attempts")
    op.drop_index(op.f("ix_job_attempts_lease_token"), table_name="job_attempts")
    op.drop_index("ix_job_attempts_lease", table_name="job_attempts")
    op.drop_index(op.f("ix_job_attempts_job_id"), table_name="job_attempts")
    op.drop_index(op.f("ix_job_attempts_heartbeat_at"), table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_index("ix_artifacts_workflow_type", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_workflow_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_lifecycle_status"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_job_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_gdrive_file_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_artifact_type"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_jobs_workflow_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_stage"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index("ix_jobs_claim_poll", table_name="jobs")
    op.drop_index(op.f("ix_jobs_available_at"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_workflows_status_stage", table_name="workflows")
    op.drop_index(op.f("ix_workflows_status"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_idempotency_key"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_current_stage"), table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
